### ISSUE TITLE
A problem about running "demo.py"

### ISSUE THREAD

**Issue by liujs11528** [walsvid/Pixel2MeshPlusPlus#12]
Hello, I used **2080ti, tensorflow-gpu 1.12.0, CUDA 10.0.130, cudnn7.6.4** to run the code "**demo.py**", but I got a problem "Traceback (most recent call last):
  File "E:/pythondata/Pixel2MeshPlusPlus-master/demo.py", line 12, in <module>
    from modules.models_mvp2m import MeshNetMVP2M as MVP2MNet
  File "E:\pythondata\Pixel2MeshPlusPlus-master\modules\models_mvp2m.py", line 9, in <module>
    from modules.losses import mesh_loss, laplace_loss
  File "E:\pythondata\Pixel2MeshPlusPlus-master\modules\losses.py", line 6, in <module>
    from modules.chamfer import nn_distance
  File "E:\pythondata\Pixel2MeshPlusPlus-master\modules\chamfer.py", line 5, in <module>
    nn_distance_module = tf.load_op_library('./external/tf_nndistance_so.so')
  File "D:\anaconda\anaconda\envs\tf1.12\lib\site-packages\tensorflow\python\framework\load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
**tensorflow.python.framework.errors_impl.NotFoundError: .\external\tf_nndistance_so.so not found**

Process finished with exit code 1
"
**I tried to read this file with absolute path, but it didn't work either.** Below is the package I used
absl-py (0.9.0)
astor (0.8.1)
certifi (2016.2.28)
gast (0.3.3)
grpcio (1.30.0)
h5py (2.10.0)
importlib-metadata (1.7.0)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.2)
Markdown (3.2.2)
numpy (1.19.0)
opencv-python (4.3.0.36)
Pillow (7.2.0)
pip (9.0.1)
protobuf (3.12.2)
scipy (1.5.1)
setuptools (36.4.0)
six (1.15.0)
tensorboard (1.12.2)
tensorflow (1.12.0)
termcolor (1.1.0)
tflearn (0.3.2)
Werkzeug (1.0.1)
wheel (0.29.0)
wincertstore (0.2)
zipp (3.1.0)
Hope for your reply~

**Comment by lkf1996** [comment]
Ubuntu or Windows？  This error will occur in Windows

**Comment by liujs11528** [comment]
> Ubuntu or Windows？ This error will occur in Windows

Windows. So is there a solution to this problem in windows? Or is it necessary to use windows?Thanks！

**Comment by walsvid** [comment]
Hi, please refer to this section of our readme to compile CUDA op: https://github.com/walsvid/Pixel2MeshPlusPlus#compile-cuda-op. As for compiling CUDA on windows, I think a better way is to refer to the official tutorial of Tensorflow(the link also list in our readme).

**Comment by NaveedMazhar-eng** [comment]
hello i am facing this issue in ubuntu and even on your Google Colab demo. Please help. and before you answer please know that I am very new to programming so complex solutions will be hard for me to follow. Thanks! Hope to hear from you soon

**Comment by walsvid** [comment]
> hello i am facing this issue in ubuntu and even on your Google Colab demo. Please help. and before you answer please know that I am very new to programming so complex solutions will be hard for me to follow. Thanks! Hope to hear from you soon

Hi @NaveedMazhar-eng, we use chamfer loss as our loss function, however the computation of chamfer loss is not implemented by TensorFlow1.x, so we use CUDA to implement it. In order to run the code you need to use `nvcc` and `g++` to compile the C++ and CUDA code. You need to use the Makefile we provide in `external` folder and change the path to your `nvcc` and `g++`

**Comment by tPPMc-cs** [comment]
Hi, I had a fatal error after make, it showed that I couldn't find the head file, is there any config file that I can set?
