### ISSUE TITLE
indices[3304] = [2, 44, 112] does not index into param shape [3,112,112,32]

### ISSUE THREAD

**Issue by camelliawb** [walsvid/Pixel2MeshPlusPlus#16]
Hi!When I run step3 train_p2mpp.py  I got error:
2020-11-22 17:39:06.603485: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[3304] = [2, 44, 112] does not index into param shape [3,112,112,32]
2020-11-22 17:39:06.608624: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[3304] = [2, 45, 112] does not index into param shape [3,112,112,32]
2020-11-22 17:39:06.681729: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[3304] = [2, 23, 56] does not index into param shape [3,56,56,64]
2020-11-22 17:39:06.684780: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: indices[3304] = [2, 22, 56] does not index into param shape [3,56,56,64]
Traceback (most recent call last):
  File "/home/fullo/.conda/envs/p2mplus/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/fullo/.conda/envs/p2mplus/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/fullo/.conda/envs/p2mplus/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[3304] = [2, 44, 112] does not index into param shape [3,112,112,32]
	 [[{{node graph_localproj_1_layer_1/GatherNd_29}} = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](meshnet/pixel2mesh/cnn/conv2d_5/Relu, graph_localproj_1_layer_1/stack_47)]]

I try google but I get any useful information.Can you help me?

**Comment by walsvid** [comment]
I'm sorry, but it's also hard for me to judge what is wrong from the information you gave. I would suggest that you can check that the tensor associated with the projection has the correct shape, and the version of TensorFlow used is consistent with README.

**Comment by camelliawb** [comment]
Hi,now I met a new problem,when I train step1, I used about one week,when I train step3 I need to spend about one month I think,I use the dataset you provide, I don't know what's wrong，can you help me ? @walsvid

**Comment by walsvid** [comment]
> Hi,now I met a new problem,when I train step1, I used about one week,when I train step3 I need to spend about one month I think,I use the dataset you provide, I don't know what's wrong，can you help me ? @walsvid

Hi @camelliawb , the training should not be so slow, maybe you can check if you are using GPU, generally speaking the training can be finished within 30+ hours or so.

**Comment by Yangleyang** [comment]
Hi, I would like to know how you solved your problem

**Comment by tPPMc-cs** [comment]
@camelliawb @walsvid @Yangleyang Hi, I encountered the same error, could you tell me how you solved your problem?
