### ISSUE TITLE
Running Demo File Shared Libraries issue 

### ISSUE THREAD

**Issue by TamourBilal6** [walsvid/Pixel2MeshPlusPlus#21]
I am facing this shared libraries error when i am trying to start demo.py 

If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    from modules.models_mvp2m import MeshNetMVP2M as MVP2MNet
  File "/content/gdrive/MyDrive/new/Pixel2MeshPlusPlus/modules/models_mvp2m.py", line 9, in <module>
    from modules.losses import mesh_loss, laplace_loss
  File "/content/gdrive/MyDrive/new/Pixel2MeshPlusPlus/modules/losses.py", line 6, in <module>
    from modules.chamfer import nn_distance
  File "/content/gdrive/MyDrive/new/Pixel2MeshPlusPlus/modules/chamfer.py", line 4, in <module>
    nn_distance_module = tf.load_op_library('./external/tf_nndistance_so.so')
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./external/tf_nndistance_so.so: cannot open shared object file: No such file or directory

**Comment by topinfrassi01** [comment]
From where do you run the python script? Because tf_nndistance_so.so is loaded from a relative path. You should run the script directly from the project's root.

If this isn't the problem, then do these files exist? If not, you should look at your cuda version (you can see it using `nvidia-smi` inside the terminal). If you use cuda9.0 you can copy the files from the `archive-cuda-9` folder, if you run 10.0, then copy from the 10.0 folder.

If you run any other version, you'll need to compile the cuda files using the procedure described inside the `Makefile` file in the `external` folder.

If this still doesn't work, you can reply to this thread I'll try to help you out.

**Comment by TamourBilal6** [comment]
I have made changes in the makefile and given path to the CUDA and Nvidia files but still facing the same issue

**Comment by TamourBilal6** [comment]
Hi @topinfrassi01 I have sort out the issue by copying files from  tf_nndistance_so.so from CUDA 9 archieve to external folder however at the very next i found out "libcudart.so.9.0: cannot open shared object file: No such file or directory" this issue. Can u plz help me out to resolve this issue. Regards

**Comment by topinfrassi01** [comment]
If libcudart 9.0 can't be found, I believe it is because you are not using CUDA 9.0. Could you maybe give me the given path for CUDA (that you put inside the Makefile) and the output of the `nvidia-smi` command?
