### ISSUE TITLE
undefined symbol related issue while running demo.py

### ISSUE THREAD

**Issue by xcugas-techno** [walsvid/Pixel2MeshPlusPlus#30]
while running demo.py on google colaboratory I got an issue: 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    from modules.models_mvp2m import MeshNetMVP2M as MVP2MNet
  File "/content/Pixel2MeshPlusPlus/modules/models_mvp2m.py", line 9, in <module>
    from modules.losses import mesh_loss, laplace_loss
  File "/content/Pixel2MeshPlusPlus/modules/losses.py", line 6, in <module>
    from modules.chamfer import nn_distance
  File "/content/Pixel2MeshPlusPlus/modules/chamfer.py", line 4, in <module>
    nn_distance_module = tf.load_op_library('./external/tf_nndistance_so.so')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)

**tensorflow.python.framework.errors_impl.NotFoundError: ./external/tf_nndistance_so.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE**

Python -> 3.6
TensorFlow -> 1.12.0
CUDA - 10.0.130
gcc-7 g++-7

can anybody helps me to solve this issue?

**Comment by topinfrassi01** [comment]
If you want to simplify your life, drop this external module and use the chamfer distance provided by tensorflow graphics. It's been working pretty well for me.
